services:
  manual:
    build: ./
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats
    command: make doc.pdf

  vignette:
    build: ./
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats
    command: make vignette

  build_doc:
    build: ./
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats/
    command: make roxygenise

  pkg_test:
    build: ./
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats/
    command: make devtools_test

  pkg_check:
    image: thomaschln/nlpembeds:latest
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats/
    command: make

  pkg_submit:
    build: ./
    volumes:
      - ./:/SummaryStats/
    working_dir: /SummaryStats/
    command: make submit

  shiny:
    build: ./
    user: shiny
    command: /usr/bin/shiny-server /srv/shiny-server/shiny-server.conf
    ports:
      - "3838:3838"
    volumes:
      - ./shiny-server:/srv/shiny-server     
      - ./data:/srv/shiny-server/data        
    environment:
      - R_MAX_MEM_SIZE=32000
    restart: always
