services:
  shiny:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./shiny-server:/srv/shiny-server
      - ./data:/srv/shiny-server/data
    environment:
      - R_MAX_MEM_SIZE=32000
    restart: always
